name:                sdl2-snake
version:             0.1.0.0
license:             Apache-2.0
author:              "Gil Mizrahi"
maintainer:          "gilmi@posteo.net"
copyright:           "2020 Gil Mizrahi"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- random
- sdl2

library:
  source-dirs: src

executables:
  app:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - base
    - sdl2-snake

